src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Proveedor</fullName>
        <active>true</active>
        <label>Proveedor</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Caja__c.object
<CustomObject>
    <fields>
        <fullName>Moneda__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Moneda</label>
        <referenceTo>Moneda__c</referenceTo>
        <relationshipLabel>Cajas</relationshipLabel>
        <relationshipName>Cajas</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Caja</label>
    <nameField>
        <label>Nombre de Caja</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cajas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Expensa__c.object
<CustomObject>
    <fields>
        <fullName>Obra__c</fullName>
        <label>Obra</label>
        <referenceTo>Obra__c</referenceTo>
        <relationshipLabel>Expensas</relationshipLabel>
        <relationshipName>Exoensas</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Expensa</label>
    <nameField>
        <label>Nombre de Expensa</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Expensas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Expensa_gasto_general__c.object
<CustomObject>
    <fields>
        <fullName>Expensa__c</fullName>
        <label>Expensa</label>
        <referenceTo>Expensa__c</referenceTo>
        <relationshipLabel>Expensas gastos generales</relationshipLabel>
        <relationshipName>Expensas_gastos_generales</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Importe__c</fullName>
        <label>Importe</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Expensa gasto general</label>
    <nameField>
        <label>Gasto general expensa</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Expensas gastos generales</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Expensa_unidad__c.object
<CustomObject>
    <fields>
        <fullName>Actualizacion_por_trigger__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Actualizacion por trigger</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Expensa__c</fullName>
        <label>Expensa</label>
        <referenceTo>Expensa__c</referenceTo>
        <relationshipLabel>Expensas unidades</relationshipLabel>
        <relationshipName>Expensas_unidades</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Fecha_pago__c</fullName>
        <label>Fecha pago</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Monto_pagado__c</fullName>
        <label>Monto pagado</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Obra__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Obra</label>
        <referenceTo>Obra__c</referenceTo>
        <relationshipLabel>Expensas unidades</relationshipLabel>
        <relationshipName>Expensas_unidades</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Saldo_inicial__c</fullName>
        <label>Saldo inicial</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Unidad__c</fullName>
        <label>Unidad</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Unidad__c.Obra__c</field>
                <operation>equals</operation>
                <valueField>$Source.Obra__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Unidad__c</referenceTo>
        <relationshipLabel>Expensas unidades</relationshipLabel>
        <relationshipName>Expensas_unidades</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Expensa unidad</label>
    <nameField>
        <displayFormat>EU-{00000000}</displayFormat>
        <label>Nombre de Expensa unidad</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expensas unidades</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Moneda__c.object
<CustomObject>
    <label>Moneda</label>
    <nameField>
        <label>Nombre de Moneda</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Monedas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Obra__c.object
<CustomObject>
    <description>Contenedor para obras de un cliente</description>
    <fields>
        <fullName>Caja_cobro_expensas__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Caja cobro expensas</label>
        <referenceTo>Caja__c</referenceTo>
        <relationshipLabel>Proyectos</relationshipLabel>
        <relationshipName>Proyectos</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Proyecto</label>
    <nameField>
        <label>Nombre de Obra</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proyectos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Unidad__c.object
<CustomObject>
    <fields>
        <fullName>Moneda__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Moneda</label>
        <referenceTo>Moneda__c</referenceTo>
        <relationshipLabel>Unidades</relationshipLabel>
        <relationshipName>Unidades</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Obra__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Obra</label>
        <referenceTo>Obra__c</referenceTo>
        <relationshipLabel>Unidades</relationshipLabel>
        <relationshipName>Unidades</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Porcentaje_expensas__c</fullName>
        <label>Porcentaje expensas</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>Unidad</label>
    <nameField>
        <label>Nombre de Unidad</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unidades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CobroExpensaUnidadTriggerTest.cls
@isTest
private class CobroExpensaUnidadTriggerTest {

    static testMethod void myUnitTest() {
        // TO DO: implement unit test
        
        Id RecordTypeIdAccount = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Proveedor').getRecordTypeId();
        Id RecordTypeIdAccountSociedad = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Sociedad desarrolladora').getRecordTypeId();
        
        Account a = new Account(name = 'test123', recordtypeid = RecordTypeIdAccount );
        insert a;

        Account so = new Account(name = 'test123', recordtypeid = RecordTypeIdAccountSociedad );
        insert so;

        Moneda__c m = new Moneda__c(name='test');
        insert m;
        
        caja__c c = new Caja__c(name='test', moneda__c = m.id);
        insert c;

        Obra__c o = new Obra__c(name='test', caja_cobro_expensas__c = c.id);
        insert o;
        
        Expensa__c e = new Expensa__c(name='test', obra__c = o.id);
        insert e;
        
        Expensa_gasto_general__c egg = new Expensa_gasto_general__c(name='test', importe__c=10, expensa__c = e.id);
        insert egg;
        
        Unidad__c u = new Unidad__c(name='1', obra__c = o.id, Porcentaje_expensas__c = 1);
        insert u;
        
        Expensa_unidad__c eu = new Expensa_unidad__c(obra__c = o.id, expensa__c = e.id, unidad__c = u.id, actualizacion_por_trigger__c= false, Saldo_inicial__c=0, Monto_pagado__c = 1, fecha_pago__c = Date.today());
        insert eu;

        eu.monto_pagado__c = 1;
        update eu;
        
        delete eu;

        Expensa__c e2 = new Expensa__c(name='test2', obra__c = o.id);
        insert e2;
        
        Expensa_gasto_general__c egg2 = new Expensa_gasto_general__c(name='test', importe__c=10, expensa__c = e2.id);
        insert egg2;
        
        Expensa_unidad__c eu2 = new Expensa_unidad__c(obra__c = o.id, expensa__c = e2.id, unidad__c = u.id, actualizacion_por_trigger__c= false, Saldo_inicial__c=0, Monto_pagado__c = 1, fecha_pago__c = Date.today());
        insert eu2;

        Expensa_unidad__c eu3 = new Expensa_unidad__c(obra__c = o.id, expensa__c = e2.id, unidad__c = u.id, actualizacion_por_trigger__c= false, Saldo_inicial__c=0);
        insert eu3;

		eu3.monto_pagado__c = 1;
		eu3.fecha_pago__c = date.today();
		update eu3;
	
    }
}