src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CBU__c</fullName>
        <label>CBU</label>
        <length>22</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Proveedor</fullName>
        <active>true</active>
        <label>Proveedor</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Caja__c.object
<CustomObject>
    <fields>
        <fullName>Moneda__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Moneda</label>
        <referenceTo>Moneda__c</referenceTo>
        <relationshipLabel>Cajas</relationshipLabel>
        <relationshipName>Cajas</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Caja</label>
    <nameField>
        <label>Nombre de Caja</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cajas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Moneda__c.object
<CustomObject>
    <label>Moneda</label>
    <nameField>
        <label>Nombre de Moneda</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Monedas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Obra__c.object
<CustomObject>
    <description>Contenedor para obras de un cliente</description>
    <fields>
        <fullName>Caja_cobro_expensas__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Caja cobro expensas</label>
        <referenceTo>Caja__c</referenceTo>
        <relationshipLabel>Proyectos</relationshipLabel>
        <relationshipName>Proyectos</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Proyecto</label>
    <nameField>
        <label>Nombre de Obra</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proyectos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Unidad__c.object
<CustomObject>
    <fields>
        <fullName>Caja_pago_broker__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Caja pago broker</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Moneda_comision__c</field>
                <operation>equals</operation>
                <valueField>Caja__c.Moneda__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Caja__c</referenceTo>
        <relationshipLabel>Unidades (Caja pago broker)</relationshipLabel>
        <relationshipName>Unidades1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Fecha_pago_comision_broker__c</fullName>
        <label>Fecha pago comisión broker</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Fecha_pago_comision_comercial__c</fullName>
        <label>Fecha pago comisión comercial</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Importe_pagado_broker__c</fullName>
        <label>Importe pagado broker</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Importe_pagado_comision_comercial__c</fullName>
        <label>Importe pagado comision comercial</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Moneda__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Moneda</label>
        <referenceTo>Moneda__c</referenceTo>
        <relationshipLabel>Unidades</relationshipLabel>
        <relationshipName>Unidades</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Moneda_comision__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Moneda comision</label>
        <referenceTo>Moneda__c</referenceTo>
        <relationshipLabel>Unidades (Moneda comision)</relationshipLabel>
        <relationshipName>Unidades1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Obra__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Obra</label>
        <referenceTo>Obra__c</referenceTo>
        <relationshipLabel>Unidades</relationshipLabel>
        <relationshipName>Unidades</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Porcentaje_expensas__c</fullName>
        <label>Porcentaje expensas</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>Unidad</label>
    <nameField>
        <label>Nombre de Unidad</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unidades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/UnidadPagoComisionTriggerTest.cls
@isTest
private class UnidadPagoComisionTriggerTest {
    static testMethod void myUnitTest() {
        // TO DO: implement unit test
        
        Id RecordTypeIdAccount = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Proveedor').getRecordTypeId();
        Id RecordTypeIdAccountSociedad = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Sociedad desarrolladora').getRecordTypeId();
        
        Account a = new Account(name = 'test123', recordtypeid = RecordTypeIdAccount, cbu__c = '1234567890123456789012' );
        insert a;

        Account so = new Account(name = 'test123', recordtypeid = RecordTypeIdAccountSociedad , cbu__c = '1234567890123456789012');
        insert so;

        Moneda__c m = new Moneda__c(name='test');
        insert m;
        
        caja__c c = new Caja__c(name='test', moneda__c = m.id);
        insert c;

        Obra__c o = new Obra__c(name='test', caja_cobro_expensas__c = c.id);
        insert o;
        
        Unidad__c u = new Unidad__c(name='1', Moneda_comision__c = m.id,  obra__c = o.id, Porcentaje_expensas__c = 1, Fecha_pago_comision_broker__c = date.today(), Fecha_pago_comision_comercial__c = date.today(), Importe_pagado_broker__c = 1, Importe_pagado_comision_comercial__c = 1, Caja_pago_broker__c = c.id);
        insert u;

        Unidad__c u2 = new Unidad__c(name='1',Moneda_comision__c = m.id, obra__c = o.id, Porcentaje_expensas__c = 1, Caja_pago_broker__c = c.id);
        insert u2;
                
        u2.Importe_pagado_broker__c = 1;
        u2.Fecha_pago_comision_broker__c = date.today();
        u2.Importe_pagado_comision_comercial__c = 1;
        u2.Fecha_pago_comision_comercial__c = date.today();
        update u2;
    
    }
}