src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CBU__c</fullName>
        <label>CBU</label>
        <length>22</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Proveedor</fullName>
        <active>true</active>
        <label>Proveedor</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contrato__c.object
<CustomObject>
    <fields>
        <fullName>Moneda__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Moneda</label>
        <referenceTo>Moneda__c</referenceTo>
        <relationshipLabel>Contratos</relationshipLabel>
        <relationshipName>Contratos</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Monto__c</fullName>
        <label>Monto</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Obra__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Obra</label>
        <referenceTo>Obra__c</referenceTo>
        <relationshipName>Contratos1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Orden_de_compra__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Orden de compra</label>
        <referenceTo>Orden_de_compra__c</referenceTo>
        <relationshipLabel>Contratos</relationshipLabel>
        <relationshipName>Contratos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Proveedor__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Proveedor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Proveedor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contratos (Proveedor)</relationshipLabel>
        <relationshipName>Contratos</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contrato</label>
    <nameField>
        <label>Nombre de Contrato</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contratos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Factura__c.object
<CustomObject>
    <fields>
        <fullName>Moneda__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Moneda</label>
        <referenceTo>Moneda__c</referenceTo>
        <relationshipLabel>Facturas</relationshipLabel>
        <relationshipName>Facturas</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Orden_de_compra__c</fullName>
        <label>Orden de compra</label>
        <referenceTo>Orden_de_compra__c</referenceTo>
        <relationshipLabel>Facturas</relationshipLabel>
        <relationshipName>Facturas</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Responsable_carga__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Responsable carga</label>
        <referenceTo>Responsable__c</referenceTo>
        <relationshipLabel>Facturas</relationshipLabel>
        <relationshipName>Facturas</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sociedad__c</fullName>
        <formula>Orden_de_compra__r.Sociedad__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sociedad</label>
        <type>Text</type>
    </fields>
    <label>Factura</label>
    <nameField>
        <label>Nombre de Factura</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Facturas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Formula_mayor_costo__c.object
<CustomObject>
    <fields>
        <fullName>Moneda__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Moneda</label>
        <referenceTo>Moneda__c</referenceTo>
        <relationshipName>Mayores_costos</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Formula Mayor costo</label>
    <nameField>
        <displayFormat>MYC-{00000000}</displayFormat>
        <label>Nombre de Mayor costo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Formula Mayores costos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Orden_de_compra__c.object
<CustomObject>
    <fields>
        <fullName>Moneda__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Moneda</label>
        <referenceTo>Moneda__c</referenceTo>
        <relationshipLabel>Ordenes de compra</relationshipLabel>
        <relationshipName>Ordenes_de_compra</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Obra__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Obra</label>
        <referenceTo>Obra__c</referenceTo>
        <relationshipLabel>Ordenes de compra</relationshipLabel>
        <relationshipName>Ordenes_de_compra</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Presupuesto__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Presupuesto</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Proveedor__c</field>
                <operation>equals</operation>
                <valueField>Presupuesto_base__c.Proveedor__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Presupuesto_base__c</referenceTo>
        <relationshipLabel>Ordenes de compra</relationshipLabel>
        <relationshipName>Ordenes_de_compra</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Proveedor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Proveedor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Proveedor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Ordenes de compra</relationshipLabel>
        <relationshipName>Ordenes_de_compra</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Responsable_carga__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Responsable carga</label>
        <referenceTo>Responsable__c</referenceTo>
        <relationshipLabel>Ordenes de compra</relationshipLabel>
        <relationshipName>Ordenes_de_compra</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sociedad__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Sociedad</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Sociedad desarrolladora</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Ordenes de compra (Sociedad)</relationshipLabel>
        <relationshipName>Ordenes_de_compra1</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Orden de compra</label>
    <nameField>
        <label>Nombre de Orden de compra</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ordenes de compra</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Orden_de_compra_entrega__c.object
<CustomObject>
    <fields>
        <fullName>Cantidad__c</fullName>
        <label>Cantidad</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Orden_de_compra__c</fullName>
        <label>Orden de compra</label>
        <referenceTo>Orden_de_compra__c</referenceTo>
        <relationshipName>Orden_de_compra_entregas</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Valor_unitario__c</fullName>
        <label>Valor unitario</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Orden de compra detalle</label>
    <nameField>
        <displayFormat>OCE-{00000000}</displayFormat>
        <label>Nombre de Orde de compra entregas</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orden de compra detalles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Presupuesto_base__c.object
<CustomObject>
    <fields>
        <fullName>Moneda__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Moneda</label>
        <referenceTo>Moneda__c</referenceTo>
        <relationshipLabel>Presupuestos base</relationshipLabel>
        <relationshipName>Presupuestos_base</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Monto__c</fullName>
        <label>Monto</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Obra__c</fullName>
        <label>Obra</label>
        <referenceTo>Obra__c</referenceTo>
        <relationshipLabel>Presupuestos base</relationshipLabel>
        <relationshipName>Presupuestos_base</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Proveedor__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Proveedor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Proveedor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Presupuestos base</relationshipLabel>
        <relationshipName>Presupuestos_base</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Responsable_carga__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Responsable carga</label>
        <referenceTo>Responsable__c</referenceTo>
        <relationshipLabel>Presupuestos base</relationshipLabel>
        <relationshipName>Presupuestos_base</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sociedad__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sociedad</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Sociedad desarrolladora</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Presupuestos base (Sociedad)</relationshipLabel>
        <relationshipName>Presupuestos_base1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Presupuesto base</label>
    <nameField>
        <label>Nombre de Presupuesto base</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Presupuestos base</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Responsable__c.object
<CustomObject>
    <fields>
        <fullName>Sociedad__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sociedad</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Sociedad desarrolladora</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Staff</relationshipLabel>
        <relationshipName>Staff</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Staff</label>
    <nameField>
        <label>Nombre de Staff</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Staff</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ActualizarFacturasTest.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class ActualizarFacturasTest {

    static testMethod void myUnitTest() {


        Id RecordTypeIdAccount = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Proveedor').getRecordTypeId();
        Id RecordTypeIdAccountSociedad = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Sociedad desarrolladora').getRecordTypeId();
        
        Account a = new Account(name = 'test123', recordtypeid = RecordTypeIdAccount , cbu__c = '1234567890123456789012');
        insert a;

        Account so = new Account(name = 'test123', recordtypeid = RecordTypeIdAccountSociedad , cbu__c = '1234567890123456789012');
        insert so;

        Moneda__c m = new Moneda__c(name = 'moneda test');
        insert m;

        Obra__c o = new Obra__c(name='test');
        insert o;
        
        Responsable__c r = new Responsable__c(name = 'test');
        insert r;

        Presupuesto_base__c p = new Presupuesto_base__c(name='test', monto__c = 1, obra__c = o.id, proveedor__c = a.id, moneda__c = m.id, responsable_carga__c = r.id);
        insert p;
        
        Orden_de_compra__c oc = new Orden_de_compra__c(name='oc', proveedor__c = a.id, obra__c = o.id, presupuesto__c = p.id, moneda__c = m.id, responsable_carga__c = r.id, sociedad__c = so.id);
        insert oc;

        Orden_de_compra_entrega__c ocd = new Orden_de_compra_entrega__c(orden_de_compra__c = oc.id, cantidad__c = 1, valor_unitario__c = 100);
        insert ocd;

        Contrato__c c = new Contrato__c(name = 'test', moneda__c = m.id, orden_de_compra__c = oc.id, proveedor__c = a.id);
        insert c;
        
        Indicador__c ind = new Indicador__c(name = 'indicador1');
        insert ind;
        Indicador__c ind2 = new Indicador__c(name = 'indicador2');
        insert ind2;
        
        Indicador_valor__c iv = new Indicador_valor__c(Indicador__c = ind.id, Valor__c = 100, Periodo__c = '12-2015');
        insert iv;
        Indicador_valor__c iv2 = new Indicador_valor__c(Indicador__c = ind.id, Valor__c = 101, Periodo__c = '01-2016');
        insert iv2;
        
        Indicador_valor__c iv3 = new Indicador_valor__c(Indicador__c = ind2.id, Valor__c = 100, Periodo__c = '12-2015');
        insert iv3;
        Indicador_valor__c iv4 = new Indicador_valor__c(Indicador__c = ind2.id, Valor__c = 101, Periodo__c = '01-2016');
        insert iv4;
        
        Formula_mayor_costo__c fm = new Formula_mayor_costo__c(Contrato__c = c.id, Indicador__c = ind.id, Porcentaje_incidencia__c = 10, Fecha_base__c = '12-2015');
        insert fm;

        Factura__c f = new Factura__c(name='0001', numero__c='0001-00000001', Importe_neto__c = 50);
        f.contrato__c = c.id;
        f.orden_de_compra__c = oc.id;
        f.Periodo_certificacion__c = '12-2015';
        f.Periodo_control_documentacion__c = '12-2015';
        f.certificado_verde_nuevo__c = 1;
        //f.proveedor__c = a.id;
        f.numero_de_certificado__c = 1;
        //f.sociedad_que_desarrolla__c = so.Id; 
        f.coeficiente_provisorio__c = 'SI';
        insert f;


        f = new Factura__c(name='0002', numero__c='0001-00000002', Importe_neto__c = 50);
        f.contrato__c = c.id;
        f.orden_de_compra__c = oc.id;
        f.Periodo_certificacion__c = '02-2016';
        f.Periodo_control_documentacion__c = '12-2015';
        f.certificado_verde_nuevo__c = 1;
        //f.proveedor__c = a.id;
        f.numero_de_certificado__c = 1;
        //f.sociedad_que_desarrolla__c = so.Id; 
        f.coeficiente_provisorio__c = 'SI';
        insert f;

        PageReference pageRef = Page.Actualizar_facturas;
        Test.setCurrentPage(pageRef); 
        
        List <Indicador__c> inds = new List<Indicador__c>();
        inds.add(ind);
        Apexpages.StandardSetController sc = new Apexpages.StandardSetController(inds);
        ActualizarFacturas ext = new ActualizarFacturas(sc);

        pageRef.getParameters().put('name', 'Test Value');

        ext.doSomething();
        ext.doSomethingMore();
        ext.updateIndicadores();
        ext.updateIndicadoresNoencontrados();
        //System.assertEquals('/apex/success', nextPage);
        
    }
}