src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CBU__c</fullName>
        <label>CBU</label>
        <length>22</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Comercializadora</fullName>
        <active>true</active>
        <label>Comercializadora</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Moneda__c.object
<CustomObject>
    <label>Moneda</label>
    <nameField>
        <label>Nombre de Moneda</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Monedas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Objetivo_De_venta__c.object
<CustomObject>
    <description>Objetivos de venta de unidades</description>
    <fields>
        <fullName>Comercializadora__c</fullName>
        <label>Comercializadora</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Comercializadora</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Objetivos De Venta</relationshipLabel>
        <relationshipName>Objetivos_De_Venta</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Meta_en_dolares__c</fullName>
        <label>Meta en dolares</label>
        <summarizedField>Objetivo_del_mes__c.Meta_en_dolares__c</summarizedField>
        <summaryForeignKey>Objetivo_del_mes__c.Objetivo_De_Venta__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Proyecto__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Proyecto</label>
        <referenceTo>Obra__c</referenceTo>
        <relationshipLabel>Objetivos De Venta</relationshipLabel>
        <relationshipName>Objetivos_De_Venta</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Objetivo De Venta</label>
    <nameField>
        <label>Nombre de Objetivo De venta</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Objetivos De Venta</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Objetivo_del_mes__c.object
<CustomObject>
    <fields>
        <fullName>Comercializadora__c</fullName>
        <formula>Objetivo_De_Venta__r.Comercializadora__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Comercializadora</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mes__c</fullName>
        <label>Mes</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Meta_en_dolares__c</fullName>
        <label>Meta en dolares</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Monto_actual_vendido__c</fullName>
        <label>Monto actual vendido</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Objetivo_De_Venta__c</fullName>
        <label>Objetivo De Venta</label>
        <referenceTo>Objetivo_De_venta__c</referenceTo>
        <relationshipLabel>Objetivos del mes</relationshipLabel>
        <relationshipName>Objetivos_del_mes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Proyecto__c</fullName>
        <formula>Objetivo_De_Venta__r.Proyecto__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Proyecto</label>
        <type>Text</type>
    </fields>
    <label>Objetivo del mes</label>
    <nameField>
        <label>Nombre de Objetivo del mes</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Objetivos del mes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Obra__c.object
<CustomObject>
    <description>Contenedor para obras de un cliente</description>
    <fields>
        <fullName>Proyecto__c</fullName>
        <label>Proyecto</label>
        <type>TextArea</type>
    </fields>
    <label>Proyecto</label>
    <nameField>
        <label>Nombre de Obra</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proyectos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Unidad__c.object
<CustomObject>
    <fields>
        <fullName>Comercializadora__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Comercializadora</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Comercializadora</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Unidades (Comercializadora)</relationshipLabel>
        <relationshipName>Unidades1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Estado__c</fullName>
        <label>Estado</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Disponible</fullName>
                </value>
                <value>
                    <fullName>Vendida</fullName>
                </value>
                <value>
                    <fullName>Reservado</fullName>
                </value>
                <value>
                    <fullName>Posecion</fullName>
                </value>
                <value>
                    <fullName>Escriturado</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Fecha_boleto__c</fullName>
        <label>Fecha boleto</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Moneda__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Moneda</label>
        <referenceTo>Moneda__c</referenceTo>
        <relationshipLabel>Unidades</relationshipLabel>
        <relationshipName>Unidades</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Moneda_comision__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Moneda comision</label>
        <referenceTo>Moneda__c</referenceTo>
        <relationshipLabel>Unidades (Moneda comision)</relationshipLabel>
        <relationshipName>Unidades1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Obra__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Obra</label>
        <referenceTo>Obra__c</referenceTo>
        <relationshipLabel>Unidades</relationshipLabel>
        <relationshipName>Unidades</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Valor_real_operacion__c</fullName>
        <label>Valor real operacion</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Unidad</label>
    <nameField>
        <label>Nombre de Unidad</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unidades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/TestUnidadVenta.cls
//probar todos los casos con la funcion add days.
@isTest
private class TestUnidadVenta {
    static testMethod void TestUnidadVenta(){

        Id RecordTypeIdAccount = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Comercializadora').getRecordTypeId();
        
            Account a = new Account(name = 'test123', recordtypeid = RecordTypeIdAccount, CBU__c = '1111111111111111111111' );
            insert a;

            Id RecordTypeIdAccount2 = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Comercializadora').getRecordTypeId();
        
            Account a2 = new Account(name = 'test123', recordtypeid = RecordTypeIdAccount2, CBU__c = '1111111111111111111112' );
            insert a2;

            Moneda__c m = new Moneda__c(name='test');
            insert m;

            Obra__c o = new Obra__c(name='test');
            insert o;

            Objetivo_De_venta__c odv = new Objetivo_De_venta__c(name = 'test',Comercializadora__c = a.id,  Proyecto__c = o.id);
            insert odv;
            
            Objetivo_del_mes__c odm = new Objetivo_del_mes__c(name = 'test', Meta_en_dolares__c = 30000 ,Monto_actual_vendido__c = 0, Objetivo_De_Venta__c = odv.id , mes__c= date.today());
            insert odm;


            Unidad__c u = new Unidad__c(name='1',Moneda_comision__c = m.id,  obra__c = o.id, Comercializadora__c = a.id , Estado__c = 'Vendida' , 	Fecha_boleto__c = date.today() , Valor_real_operacion__c = 20000);
            insert u;
        
            Unidad__c u2 = new Unidad__c(name='2',Moneda_comision__c = m.id,  obra__c = o.id, Comercializadora__c = a.id , Estado__c = 'Disponible' , 	Fecha_boleto__c = date.today() , Valor_real_operacion__c = 20000);
            insert u2;

            Unidad__c u4 = new Unidad__c(name='2',Moneda_comision__c = m.id,  obra__c = o.id, Comercializadora__c = a.id , Estado__c = 'Disponible' , 	Fecha_boleto__c = date.today().addDays(45), Valor_real_operacion__c = 20000);
            insert u4;
           
            Unidad__c u5 = new Unidad__c(name='2',Moneda_comision__c = m.id,  obra__c = o.id, Comercializadora__c = a.id , Estado__c = 'Vendida' , 	Fecha_boleto__c = date.today().addDays(45), Valor_real_operacion__c = 20000);
            insert u5;
            //System.debug('MATU'+ date.today().addDays(45));

             Unidad__c u6 = new Unidad__c(name='1',Moneda_comision__c = m.id,  obra__c = null, Comercializadora__c = a.id , Estado__c = 'Vendida' , 	Fecha_boleto__c = date.today() , Valor_real_operacion__c = 20000);
             insert u6;

             u4.Estado__c = 'Vendida';
             update u4;

         //   u6.Estado__c = 'Disponible';
         //   update u6;

            odm.Monto_actual_vendido__c = 1;
            update odm;

            Unidad__c u3 = new Unidad__c(name='2',Moneda_comision__c = m.id,  obra__c = o.id, Comercializadora__c = a.id , Estado__c = 'Vendida' , 	Fecha_boleto__c = date.today() , Valor_real_operacion__c = 20000);
            insert u3;

            odm.Monto_actual_vendido__c = 0;
            update odm;

            u.Estado__c = 'Disponible';
            update u;
        //monto actual en 0 
        
              u2.Estado__c = 'Vendida';
            update u2;
            //monto actual en 0
            u.Estado__c = 'Vendida';
           odm.Monto_actual_vendido__c = 1;
            update u;
            update odm;
           //monto actual en 1
             u.Estado__c = 'Disponible';
           odm.Monto_actual_vendido__c = 1;
            update u;
            update odm;
           //monto actual en 1
           
            delete u2;
            
    }
}