src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Propietario</fullName>
        <active>true</active>
        <label>Propietario</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Caja__c.object
<CustomObject>
    <fields>
        <fullName>Moneda__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Moneda</label>
        <referenceTo>Moneda__c</referenceTo>
        <relationshipLabel>Cajas</relationshipLabel>
        <relationshipName>Cajas</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Caja</label>
    <nameField>
        <label>Nombre de Caja</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cajas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Cobro_unidad__c.object
<CustomObject>
    <fields>
        <fullName>Caja__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Caja</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Caja__c.Moneda__c</field>
                <operation>equals</operation>
                <valueField>$Source.Moneda__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Caja__c</referenceTo>
        <relationshipLabel>Plan de pagos</relationshipLabel>
        <relationshipName>Plan_de_pagos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Fecha_cobro__c</fullName>
        <label>Fecha cobro</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Importe__c</fullName>
        <label>Importe</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Importe_cobrado__c</fullName>
        <label>Importe cobrado</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Moneda__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Moneda</label>
        <referenceTo>Moneda__c</referenceTo>
        <relationshipName>Cobro_unidades</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Unidad__c</fullName>
        <label>Unidad</label>
        <referenceTo>Unidad__c</referenceTo>
        <relationshipLabel>Plan de pagos</relationshipLabel>
        <relationshipName>Cobro_unidades</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Vencimiento__c</fullName>
        <label>Vencimiento</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Plan de pago</label>
    <nameField>
        <label>Cuota</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plan de pagos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Expensa__c.object
<CustomObject>
    <fields>
        <fullName>Obra__c</fullName>
        <label>Obra</label>
        <referenceTo>Obra__c</referenceTo>
        <relationshipLabel>Expensas</relationshipLabel>
        <relationshipName>Exoensas</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Expensa</label>
    <nameField>
        <label>Nombre de Expensa</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Expensas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Expensa_gasto_general__c.object
<CustomObject>
    <fields>
        <fullName>Expensa__c</fullName>
        <label>Expensa</label>
        <referenceTo>Expensa__c</referenceTo>
        <relationshipLabel>Expensas gastos generales</relationshipLabel>
        <relationshipName>Expensas_gastos_generales</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Importe__c</fullName>
        <label>Importe</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Expensa gasto general</label>
    <nameField>
        <label>Gasto general expensa</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Expensas gastos generales</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Expensa_unidad__c.object
<CustomObject>
    <fields>
        <fullName>Expensa__c</fullName>
        <label>Expensa</label>
        <referenceTo>Expensa__c</referenceTo>
        <relationshipLabel>Expensas unidades</relationshipLabel>
        <relationshipName>Expensas_unidades</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Fecha_pago__c</fullName>
        <label>Fecha pago</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Monto_pagado__c</fullName>
        <label>Monto pagado</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Obra__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Obra</label>
        <referenceTo>Obra__c</referenceTo>
        <relationshipLabel>Expensas unidades</relationshipLabel>
        <relationshipName>Expensas_unidades</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Unidad__c</fullName>
        <label>Unidad</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Unidad__c.Obra__c</field>
                <operation>equals</operation>
                <valueField>$Source.Obra__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Unidad__c</referenceTo>
        <relationshipLabel>Expensas unidades</relationshipLabel>
        <relationshipName>Expensas_unidades</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Expensa unidad</label>
    <nameField>
        <displayFormat>EU-{00000000}</displayFormat>
        <label>Nombre de Expensa unidad</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expensas unidades</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Moneda__c.object
<CustomObject>
    <label>Moneda</label>
    <nameField>
        <label>Nombre de Moneda</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Monedas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Obra__c.object
<CustomObject>
    <description>Contenedor para obras de un cliente</description>
    <fields>
        <fullName>Caja_cobro_expensas__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Caja cobro expensas</label>
        <referenceTo>Caja__c</referenceTo>
        <relationshipLabel>Proyectos</relationshipLabel>
        <relationshipName>Proyectos</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Proyecto</label>
    <nameField>
        <label>Nombre de Obra</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proyectos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Unidad__c.object
<CustomObject>
    <fields>
        <fullName>Moneda__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Moneda</label>
        <referenceTo>Moneda__c</referenceTo>
        <relationshipLabel>Unidades</relationshipLabel>
        <relationshipName>Unidades</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Obra__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Obra</label>
        <referenceTo>Obra__c</referenceTo>
        <relationshipLabel>Unidades</relationshipLabel>
        <relationshipName>Unidades</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Porcentaje_expensas__c</fullName>
        <label>Porcentaje expensas</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Propietario_principal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Propietario principal</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Propietario</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Unidades (Propietario Principal)</relationshipLabel>
        <relationshipName>Unidades</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Unidad</label>
    <nameField>
        <label>Nombre de Unidad</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unidades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/myCobroUnidadExtensionTest.cls
@isTest
private class myCobroUnidadExtensionTest {

    static testMethod void myUnitTest() {


        Id RecordTypeIdAccount = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Propietario').getRecordTypeId();
        Id RecordTypeIdAccountSociedad = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Sociedad desarrolladora').getRecordTypeId();
        
        Account a = new Account(name = 'test123', recordtypeid = RecordTypeIdAccount );
        insert a;

        Account so = new Account(name = 'test123', recordtypeid = RecordTypeIdAccountSociedad );
        insert so;

        Moneda__c m = new Moneda__c(name = 'moneda test');
        insert m;

        caja__c c = new Caja__c(name='test', moneda__c = m.id);
        insert c;

        Obra__c o = new Obra__c(name='test', caja_cobro_expensas__c = c.id);
        insert o;
    
        Unidad__c u = new Unidad__c(name='u', obra__c = o.id, Porcentaje_expensas__c = 5, propietario_principal__c = a.id);
        insert u;

        Expensa__c e = new Expensa__c(name='e', obra__c = o.id);
        insert e;
        
        Expensa_gasto_general__c eg = new Expensa_gasto_general__c(name = 'luz',expensa__c = e.id, importe__c = 10);
        insert eg;
        
        Expensa_unidad__c eu = new Expensa_unidad__c(Expensa__c = e.id, Unidad__c = u.id, Obra__c = o.id, Monto_pagado__c = 1, fecha_pago__c = date.today());
        insert eu;

        Cobro_unidad__c cu = new Cobro_unidad__c(unidad__c = u.id, importe_cobrado__c = 1, caja__c = c.id, fecha_cobro__c = Date.Today(), vencimiento__c = date.today(), moneda__c = m.id);
        insert cu;

        cu.importe_cobrado__c = 1;
        update cu;
        
        delete cu;

        Cobro_unidad__c cu2 = new Cobro_unidad__c(unidad__c = u.id, vencimiento__c = date.today(), moneda__c = m.id);
        insert cu2;

        cu2.importe_cobrado__c = 1;
        cu2.caja__c = c.id;
        cu2.fecha_cobro__c = date.today();
        update cu2;

        
        PageReference pageRef = Page.vf_recibo_pago_unidad  ;
        Test.setCurrentPage(pageRef); 

        pageRef.getParameters().put('id',cu.id);
        
        List <Cobro_Unidad__c> inds = new List<Cobro_Unidad__c>();
        inds.add(cu);

        
        Apexpages.StandardController sc = new Apexpages.StandardController(cu);
        myCobroUnidadExtension ext = new myCobroUnidadExtension(sc);


        //System.assertEquals('/apex/success', nextPage);
 
}

}