src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Propietario</fullName>
        <active>true</active>
        <label>Propietario</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Cobro_unidad__c.object
<CustomObject>
    <fields>
        <fullName>Importe_cobrado__c</fullName>
        <label>Importe cobrado</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Unidad__c</fullName>
        <label>Unidad</label>
        <referenceTo>Unidad__c</referenceTo>
        <relationshipLabel>Plan de pagos</relationshipLabel>
        <relationshipName>Cobro_unidades</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Plan de pago</label>
    <nameField>
        <label>Cuota</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plan de pagos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Unidad__c.object
<CustomObject>
    <fields>
        <fullName>Propietario_principal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Propietario principal</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Propietario</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Unidades (Propietario Principal)</relationshipLabel>
        <relationshipName>Unidades</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Unidad</label>
    <nameField>
        <label>Nombre de Unidad</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unidades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/myCobroUnidadExtension.cls
public class myCobroUnidadExtension {

    private final Cobro_unidad__c cobro;   
    public Unidad__c Unidad {get;set;}   
    public Account propietario {get;set;}  
    public  Num2Text nwcObj ;
    public String numinWords {get; set;}

    public myCobroUnidadExtension(ApexPages.StandardController stdController) {

        this.cobro = (Cobro_unidad__c)stdController.getRecord();
        this.unidad = [SELECT Id, Name, propietario_principal__c    FROM unidad__c WHERE id =: this.cobro.unidad__c  LIMIT 1];
        this.propietario = [SELECT Id, Name   FROM account WHERE id =: this.unidad.propietario_principal__c  LIMIT 1];
        this.nwcObj = new Num2Text();
        this.numInWords = nwcObj.getNumberTOWordConvertion(this.cobro.importe_cobrado__c);            


    }

 
    public PageReference doSomething()    
    {


        return null;
    }
    
    
    public PageReference doSomethingMore()    
    {

        PageReference pr = new PageReference('/apex/ExpensasUnidadPdf');
        pr.setRedirect(true);
        return pr;
    
    }
    
}