src/objects/Caja__c.object
<CustomObject>
    <label>Caja</label>
    <nameField>
        <label>Nombre de Caja</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cajas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Movimiento_de_caja__c.object
<CustomObject>
    <fields>
        <fullName>Caja__c</fullName>
        <label>Caja</label>
        <referenceTo>Caja__c</referenceTo>
        <relationshipLabel>Movimientos de caja</relationshipLabel>
        <relationshipName>Movimientos_de_caja</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Estado__c</fullName>
        <label>Estado</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Impactado</fullName>
                    <default>true</default>
                    <label>Impactado</label>
                </value>
                <value>
                    <fullName>Pendiente</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Fecha_movimiento__c</fullName>
        <label>Fecha movimiento</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Importe__c</fullName>
        <label>Importe</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Movimiento de caja</label>
    <nameField>
        <displayFormat>mc-{00000000}</displayFormat>
        <label>Nombre de Movimiento de caja</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Movimientos de caja</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/TestTriggerMovimientoDeCaja.cls
@isTest
    private class TestTriggerMovimientoDeCaja {
        static testMethod void TestTriggerMovimientoDeCaja(){
            Caja__c c = new Caja__c ();
            c.name = 'test';
            insert c;
            movimiento_de_caja__c mc = new movimiento_de_caja__c ( Fecha_movimiento__c = date.today(),Importe__c = 20000,Estado__c = 'Impactado', Caja__c = c.id);
            
            insert mc;
        }
    }