src/objects/Cobro_unidad__c.object
<CustomObject>
    <fields>
        <fullName>Fecha_cobro__c</fullName>
        <label>Fecha cobro</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Importe__c</fullName>
        <label>Importe</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Importe_cobrado__c</fullName>
        <label>Importe cobrado</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Moneda__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Moneda</label>
        <referenceTo>Moneda__c</referenceTo>
        <relationshipName>Cobro_unidades</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Saldo__c</fullName>
        <formula>Importe__c - Importe_cobrado__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Saldo</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Unidad__c</fullName>
        <label>Unidad</label>
        <referenceTo>Unidad__c</referenceTo>
        <relationshipLabel>Plan de pagos</relationshipLabel>
        <relationshipName>Cobro_unidades</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Vencimiento__c</fullName>
        <label>Vencimiento</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Plan de pago</label>
    <nameField>
        <label>Cuota</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plan de pagos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Moneda__c.object
<CustomObject>
    <label>Moneda</label>
    <nameField>
        <label>Nombre de Moneda</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Monedas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Unidad__c.object
<CustomObject>
    <fields>
        <fullName>Importes_pagados__c</fullName>
        <label>Importes pagados</label>
        <summarizedField>Cobro_unidad__c.Importe_cobrado__c</summarizedField>
        <summaryForeignKey>Cobro_unidad__c.Unidad__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Moneda__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Moneda</label>
        <referenceTo>Moneda__c</referenceTo>
        <relationshipLabel>Unidades</relationshipLabel>
        <relationshipName>Unidades</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Precio_de_venta__c</fullName>
        <label>Monto segun boleto</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Saldo_a_pagar__c</fullName>
        <formula>Total_a_pagar_calculado__c -   Importes_pagados__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Saldo a pagar</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_a_pagar_calculado__c</fullName>
        <label>Total a pagar segun plan de pago</label>
        <summarizedField>Cobro_unidad__c.Importe__c</summarizedField>
        <summaryForeignKey>Cobro_unidad__c.Unidad__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Unidad</label>
    <nameField>
        <label>Nombre de Unidad</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unidades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/LibreDeudaListController.cls
public class LibreDeudaListController {

    private String sortOrder = 'Vencimiento__c';
    public String libre{get;set;}   
    public Unidad__c uni{get;set;}   
 
    public PageReference doSomething()    
    {

		uni = [SELECT Id, Name, Total_a_pagar_calculado__c, Saldo_a_pagar__c, Importes_pagados__c, Precio_de_venta__c	 FROM Unidad__c WHERE id =: ApexPages.CurrentPage().getparameters().get('id')  LIMIT 1];

        List<Cobro_unidad__c> results = Database.query(
            'SELECT Id, Name, Fecha_cobro__c, Importe__c, Importe_cobrado__c, Moneda__c, Vencimiento__c ' +
            'FROM Cobro_unidad__c ' +
            'WHERE Saldo__c != 0' +
            ' AND Unidad__c = \''+ApexPages.CurrentPage().getparameters().get('id') + '\'' +
            'ORDER BY ' + sortOrder + ' ASC ' +
            'LIMIT 100'
        );
        this.libre = 'SI';
        for (Cobro_unidad__c cu : results) {
            this.libre = 'NO';
        }

        return null;
    }
    
    public List<Cobro_unidad__c> getCuotas() {
        
        List<Cobro_unidad__c> results = Database.query(
            'SELECT Id, Name, Fecha_cobro__c, Importe__c, Importe_cobrado__c, Moneda__c, Vencimiento__c ' +
            'FROM Cobro_unidad__c ' +
            'WHERE Saldo__c != 0' +
            ' AND Unidad__c = \''+ApexPages.CurrentPage().getparameters().get('id') + '\'' +
            'ORDER BY ' + sortOrder + ' ASC ' +
            'LIMIT 100'
        );
        List<Cobro_unidad__c> res = New List<Cobro_unidad__c>();
        this.libre = 'SI';
        for (Cobro_unidad__c cu : results) {
            res.add(cu);
            this.libre = 'NO';
        }
        return res;
    }
    
    public PageReference doSomethingMore()    
    {

        PageReference pr = new PageReference('/apex/LibreDeudaPdf');
        pr.setRedirect(true);
        return pr;
    
    }
    
}