src/objects/Contrato__c.object
<CustomObject>
    <fields>
        <fullName>Moneda__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Moneda</label>
        <referenceTo>Moneda__c</referenceTo>
        <relationshipLabel>Contratos</relationshipLabel>
        <relationshipName>Contratos</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Contrato</label>
    <nameField>
        <label>Nombre de Contrato</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contratos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Formula_mayor_costo__c.object
<CustomObject>
    <fields>
        <fullName>Contrato__c</fullName>
        <label>Contrato</label>
        <referenceTo>Contrato__c</referenceTo>
        <relationshipName>Mayores_costos</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Fecha_base__c</fullName>
        <label>Fecha base</label>
        <length>7</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Indicador__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Indicador</label>
        <referenceTo>Indicador__c</referenceTo>
        <relationshipName>Mayores_costos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Moneda__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Moneda</label>
        <referenceTo>Moneda__c</referenceTo>
        <relationshipName>Mayores_costos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Porcentaje_incidencia__c</fullName>
        <label>Porcentaje incidencia</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>Formula Mayor costo</label>
    <nameField>
        <displayFormat>MYC-{00000000}</displayFormat>
        <label>Nombre de Mayor costo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Formula Mayores costos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Indicador__c.object
<CustomObject>
    <label>Indicador</label>
    <nameField>
        <label>Nombre de Indicador</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Indicadores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Indicador_valor__c.object
<CustomObject>
    <fields>
        <fullName>Indicador__c</fullName>
        <label>Indicador</label>
        <referenceTo>Indicador__c</referenceTo>
        <relationshipLabel>Indicadores valores</relationshipLabel>
        <relationshipName>Indicadores_valores</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Nombre__c</fullName>
        <label>Nombre</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Periodo__c</fullName>
        <label>Periodo</label>
        <length>7</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Porcentaje_incidencia__c</fullName>
        <label>Porcentaje incidencia</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Valor__c</fullName>
        <label>Valor</label>
        <precision>18</precision>
        <scale>5</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Valor_base__c</fullName>
        <label>Valor base</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Indicador valor</label>
    <nameField>
        <displayFormat>INDVAL-{00000}</displayFormat>
        <label>Indicador valor</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Indicadores valores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Moneda__c.object
<CustomObject>
    <label>Moneda</label>
    <nameField>
        <label>Nombre de Moneda</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Monedas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CalculoMayoresCostosTest.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class CalculoMayoresCostosTest {

    static testMethod void myUnitTest() {
        // TO DO: implement unit test
        Decimal num = 10;
        
        Account a = new Account(name = 'test');
        insert a;

        Moneda__c m = new Moneda__c(name = 'moneda test');
        insert m;

        Contrato__c c = new Contrato__c(name = 'test', moneda__c = m.id);
        insert c;
        
        Indicador__c ind = new Indicador__c(name = 'indicador1');
        insert ind;
        
        Indicador_valor__c iv = new Indicador_valor__c(Indicador__c = ind.id, Valor__c = 100, Periodo__c = '12-2015');
		insert iv;
        iv = new Indicador_valor__c(Indicador__c = ind.id, Valor__c = 101, Periodo__c = '01-2016');
		insert iv;
        
        
        Formula_mayor_costo__c fm = new Formula_mayor_costo__c(Contrato__c = c.id, Indicador__c = ind.id, Porcentaje_incidencia__c = 10, Fecha_base__c = '12-2015');
        insert fm;
        
        CalculoMayoresCostos mayorCosto = new CalculoMayoresCostos();
        List<Indicador_valor__c> resultado = mayorCosto.setIndicadores('01-2016', c.Id);
            
		for (Integer i=0; i < resultado.size(); i++) {
			if (i==0){ 
				System.debug('indicador1:'+resultado[i].Valor__c);
				System.assertEquals(101, resultado[i].Valor__c );
				System.assertEquals('indicador1', resultado[i].Nombre__c );
			}
			if (i==1){ 
				System.debug('indicador2:'+resultado[i].Valor__c);
			}
			if (i==2){ 
				System.debug('indicador3:'+resultado[i].Valor__c);
			}
			if (i==3){ 
				System.debug('indicador4:'+resultado[i].Valor__c);
			}
			System.debug('base:'+resultado[i].Valor_base__c);
		}

        CalculoMayoresCostos mayorCosto2 = new CalculoMayoresCostos();
        List<Indicador_valor__c> resultado2 = mayorCosto.setIndicadores('02-2016', c.Id);
            
		for (Integer ii=0; ii < resultado2.size(); ii++) {
			if (ii==0){ 
				System.debug('indicador1:'+resultado2[ii].Valor__c);
				System.assertEquals(101, resultado2[ii].Valor__c );
				System.assertEquals('indicador1', resultado2[ii].Nombre__c );
			}
			if (ii==1){ 
				System.debug('indicador2:'+resultado2[ii].Valor__c);
			}
			if (ii==2){ 
				System.debug('indicador3:'+resultado2[ii].Valor__c);
			}
			if (ii==3){ 
				System.debug('indicador4:'+resultado2[ii].Valor__c);
			}
			System.debug('base:'+resultado2[ii].Valor_base__c);
		}


        
    }
}