src/objects/Contrato__c.object
<CustomObject>
    <label>Contrato</label>
    <nameField>
        <label>Nombre de Contrato</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contratos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Formula_mayor_costo__c.object
<CustomObject>
    <fields>
        <fullName>Contrato__c</fullName>
        <label>Contrato</label>
        <referenceTo>Contrato__c</referenceTo>
        <relationshipName>Mayores_costos</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Fecha_base__c</fullName>
        <label>Fecha base</label>
        <length>7</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Indicador__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Indicador</label>
        <referenceTo>Indicador__c</referenceTo>
        <relationshipName>Mayores_costos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Porcentaje_incidencia__c</fullName>
        <label>Porcentaje incidencia</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>Formula Mayor costo</label>
    <nameField>
        <displayFormat>MYC-{00000000}</displayFormat>
        <label>Nombre de Mayor costo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Formula Mayores costos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Indicador__c.object
<CustomObject>
    <label>Indicador</label>
    <nameField>
        <label>Nombre de Indicador</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Indicadores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Indicador_valor__c.object
<CustomObject>
    <fields>
        <fullName>Coeficiente_provisorio__c</fullName>
        <label>Coeficiente provisorio</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Indicador__c</fullName>
        <label>Indicador</label>
        <referenceTo>Indicador__c</referenceTo>
        <relationshipLabel>Indicadores valores</relationshipLabel>
        <relationshipName>Indicadores_valores</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Nombre__c</fullName>
        <label>Nombre</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Periodo__c</fullName>
        <label>Periodo</label>
        <length>7</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Porcentaje_incidencia__c</fullName>
        <label>Porcentaje incidencia</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Valor__c</fullName>
        <label>Valor</label>
        <precision>18</precision>
        <scale>5</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Valor_base__c</fullName>
        <label>Valor base</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Indicador valor</label>
    <nameField>
        <displayFormat>INDVAL-{00000}</displayFormat>
        <label>Indicador valor</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Indicadores valores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/CalculoMayoresCostos.cls
public with sharing class CalculoMayoresCostos {
    public List<Indicador_valor__c> setIndicadores(String periodo, String contrato) {
		List<Formula_mayor_costo__c> queryResults = [SELECT Indicador__c,Porcentaje_incidencia__c, Fecha_base__c FROM Formula_mayor_costo__c where Contrato__c =:contrato ];
		List<Indicador_valor__c> indicadores = new List<Indicador_valor__c>();
	 	if (queryResults.size()>0) {
			for (Formula_mayor_costo__c o : queryResults) {
				try {
					Indicador_valor__c val = [SELECT Indicador__c, Valor__c FROM Indicador_valor__c WHERE Indicador__c =: o.Indicador__c and Periodo__c =:periodo LIMIT 1];
					Indicador__c nom = [SELECT Name FROM Indicador__c WHERE id =: val.Indicador__c  LIMIT 1];
					val.Nombre__c = nom.name;				
					Indicador_valor__c valBase = [SELECT Indicador__c, Valor__c FROM Indicador_valor__c WHERE Indicador__c =: o.Indicador__c and Periodo__c =:o.Fecha_base__c LIMIT 1];
					val.valor_base__c = valBase.Valor__c;
					val.Porcentaje_incidencia__c = o.Porcentaje_incidencia__c;
					val.coeficiente_provisorio__c = null;
					indicadores.add(val);
			 	} catch(Exception ex) {
			 		Boolean encontre = false;
			 		while (encontre == false){
						String[] strDate = periodo.split('-');
						Integer myIntDate = 1;
						Integer myIntMonth = integer.valueOf(strDate[0]);
						Integer myIntYear = integer.valueOf(strDate[1]);
						myIntMonth = myIntMonth - 1;
						if (myIntMonth <= 0 ){
							myIntMonth = 12;
							myIntYear = myIntYear -1;
						}
						Date dat = Date.newInstance(myIntYear, myIntMonth, myIntDate);
						String mes = String.valueof(dat.month()).leftpad(2, '0');
						String nuevoPeriodo = mes+'-'+dat.year();
						periodo = nuevoPeriodo;	 
				        System.debug('Nuevo periodo: '+nuevoPeriodo);
						try {
							Indicador_valor__c val = [SELECT Indicador__c, Valor__c FROM Indicador_valor__c WHERE Indicador__c =: o.Indicador__c and Periodo__c =:nuevoPeriodo LIMIT 1];
							Indicador__c nom = [SELECT Name FROM Indicador__c WHERE id =: val.Indicador__c  LIMIT 1];
							encontre = true;
							val.Nombre__c = nom.name;	
							val.coeficiente_provisorio__c = 'SI';			
							Indicador_valor__c valBase = [SELECT Indicador__c, Valor__c FROM Indicador_valor__c WHERE Indicador__c =: o.Indicador__c and Periodo__c =:o.Fecha_base__c LIMIT 1];
							val.valor_base__c = valBase.Valor__c;
							val.Porcentaje_incidencia__c = o.Porcentaje_incidencia__c;
							indicadores.add(val);
					 	} catch(Exception ex2) {				 	}
			 		}
			 	}
			}
	 	}
	 	return indicadores;
    }

}