src/objects/Expensa__c.object
<CustomObject>
    <fields>
        <fullName>Saldo_a_pagar__c</fullName>
        <formula>Gastos_generales__c  -  Montos_pagados__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Saldo a pagar</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Expensa</label>
    <nameField>
        <label>Nombre de Expensa</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Expensas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Expensa_gasto_general__c.object
<CustomObject>
    <fields>
        <fullName>Expensa__c</fullName>
        <label>Expensa</label>
        <referenceTo>Expensa__c</referenceTo>
        <relationshipLabel>Expensas gastos generales</relationshipLabel>
        <relationshipName>Expensas_gastos_generales</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Importe__c</fullName>
        <label>Importe</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Expensa gasto general</label>
    <nameField>
        <label>Gasto general expensa</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Expensas gastos generales</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Expensa_unidad__c.object
<CustomObject>
    <fields>
        <fullName>Expensa__c</fullName>
        <label>Expensa</label>
        <referenceTo>Expensa__c</referenceTo>
        <relationshipLabel>Expensas unidades</relationshipLabel>
        <relationshipName>Expensas_unidades</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Fecha_pago__c</fullName>
        <label>Fecha pago</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Monto_a_pagar__c</fullName>
        <formula>Expensa__r.Gastos_generales__c  *  Unidad__r.Porcentaje_expensas__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Monto a pagar</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Monto_pagado__c</fullName>
        <label>Monto pagado</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Saldo_a_pagar__c</fullName>
        <formula>Monto_a_pagar__c + Intereses_punitorios__c + Saldo_inicial__c  -  Monto_pagado__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Saldo a pagar</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Unidad__c</fullName>
        <label>Unidad</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Unidad__c.Obra__c</field>
                <operation>equals</operation>
                <valueField>$Source.Obra__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Unidad__c</referenceTo>
        <relationshipLabel>Expensas unidades</relationshipLabel>
        <relationshipName>Expensas_unidades</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Expensa unidad</label>
    <nameField>
        <displayFormat>EU-{00000000}</displayFormat>
        <label>Nombre de Expensa unidad</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expensas unidades</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Unidad__c.object
<CustomObject>
    <fields>
        <fullName>Saldo_a_pagar__c</fullName>
        <formula>Total_a_pagar_calculado__c -   Importes_pagados__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Saldo a pagar</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Unidad</label>
    <nameField>
        <label>Nombre de Unidad</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unidades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/myExpensaUnidadExtension.cls
public class myExpensaUnidadExtension {

    private final Expensa_unidad__c uni;   

    public myExpensaUnidadExtension(ApexPages.StandardController stdController) {
        if (!Test.isRunningTest()) stdController.addFields(new List<String>{'Id','Name', 'Expensa__c', 'Unidad__c'});

        this.uni = (Expensa_unidad__c)stdController.getRecord();
    }

 
    public PageReference doSomething()    
    {

        //this.uni = [SELECT Id, Name, Expensa__c, Monto_a_pagar__c, Fecha_pago__c, Saldo_a_pagar__c, Monto_pagado__c    FROM Expensa_unidad__c WHERE id =: ApexPages.CurrentPage().getparameters().get('id')  LIMIT 1];

        List<Expensa_gasto_general__c> results = Database.query(
            'SELECT Id, Name, Importe__c ' +
            'FROM Expensa_gasto_general__c ' +
            'WHERE Expensa__c = \''+uni.Expensa__c + '\'' +
            'LIMIT 100'
        );
        for (Expensa_gasto_general__c cu : results) {
        }

        return null;
    }
    
    public List<Expensa_gasto_general__c> getCuotas() {
        
        List<Expensa_gasto_general__c> results = Database.query(
            'SELECT Id, Name, Importe__c ' +
            'FROM Expensa_gasto_general__c ' +
            'WHERE Expensa__c = \''+uni.Expensa__c + '\'' +
            'LIMIT 100'
        );
        List<Expensa_gasto_general__c> res = New List<Expensa_gasto_general__c>();
        for (Expensa_gasto_general__c cu : results) {
            res.add(cu);
        }
        return res;
    }
    
    public PageReference doSomethingMore()    
    {

        PageReference pr = new PageReference('/apex/ExpensasUnidadPdf');
        pr.setRedirect(true);
        return pr;
    
    }
    
}