src/objects/Factura__c.object
<CustomObject>
    <fields>
        <fullName>Estado__c</fullName>
        <label>Estado</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Real</fullName>
                </value>
                <value>
                    <fullName>Provisoria</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Importe_neto__c</fullName>
        <label>Importe neto gravado</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Moneda__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Moneda</label>
        <referenceTo>Moneda__c</referenceTo>
        <relationshipLabel>Facturas</relationshipLabel>
        <relationshipName>Facturas</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Numero__c</fullName>
        <label>Número</label>
        <length>14</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Orden_de_compra__c</fullName>
        <label>Orden de compra</label>
        <referenceTo>Orden_de_compra__c</referenceTo>
        <relationshipLabel>Facturas</relationshipLabel>
        <relationshipName>Facturas</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Responsable_carga__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Responsable carga</label>
        <referenceTo>Responsable__c</referenceTo>
        <relationshipLabel>Facturas</relationshipLabel>
        <relationshipName>Facturas</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tipo_de_factura__c</fullName>
        <label>Tipo de factura</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>A</fullName>
                </value>
                <value>
                    <fullName>B</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Factura</label>
    <nameField>
        <label>Nombre de Factura</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Facturas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Moneda__c.object
<CustomObject>
    <label>Moneda</label>
    <nameField>
        <label>Nombre de Moneda</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Monedas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Orden_de_compra__c.object
<CustomObject>
    <fields>
        <fullName>Estado__c</fullName>
        <label>Estado</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Ingresada</fullName>
                    <default>true</default>
                    <label>Ingresada</label>
                </value>
                <value>
                    <fullName>Para aprobar</fullName>
                </value>
                <value>
                    <fullName>Aprobada</fullName>
                </value>
                <value>
                    <fullName>Rechazada</fullName>
                </value>
                <value>
                    <fullName>Renegociar</fullName>
                </value>
                <value>
                    <fullName>Pagada</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Moneda__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Moneda</label>
        <referenceTo>Moneda__c</referenceTo>
        <relationshipLabel>Ordenes de compra</relationshipLabel>
        <relationshipName>Ordenes_de_compra</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Responsable_carga__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Responsable carga</label>
        <referenceTo>Responsable__c</referenceTo>
        <relationshipLabel>Ordenes de compra</relationshipLabel>
        <relationshipName>Ordenes_de_compra</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Orden de compra</label>
    <nameField>
        <label>Nombre de Orden de compra</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ordenes de compra</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UAT/force-app/main/default/classes/TestTriggerFactura.cls
@isTest
//name,oc,responsabke carga,tipo de factura,estado,numero,moneda,importe neto gravado
    private class TestTriggerFactura {
        static testMethod void TestTriggerFactura(){
          //Orden_de_compra__c oc = new Orden_de_compra__c(name ='test');
          //insert oc;
          //Factura__c f = new Factura__c(name = 'test',Responsable_carga__c='test',Tipo_de_factura__c ='A',Estado__c='Real',Numero__c ='1',Moneda__c = 'Dolares',Importe_neto__c=1,Orden_de_compra__c =oc.id );
          //insert f;
          //Factura__c f2 = new Factura__c(name = 'test',Responsable_carga__c='test',Tipo_de_factura__c ='A',Estado__c='Real',Numero__c ='1',Moneda__c = 'Dolares',Importe_neto__c=1,Orden_de_compra__c =oc.id );
          //insert f2;

        }
    }