src/objects/Moneda__c.object
<CustomObject>
    <label>Moneda</label>
    <nameField>
        <label>Nombre de Moneda</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Monedas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Moneda_cotizacion__c.object
<CustomObject>
    <fields>
        <fullName>Cotizacion__c</fullName>
        <label>Cotización</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Fecha__c</fullName>
        <label>Fecha</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Moneda__c</fullName>
        <label>Moneda</label>
        <referenceTo>Moneda__c</referenceTo>
        <relationshipLabel>Moneda cotizaciones</relationshipLabel>
        <relationshipName>Moneda_cotizaciones</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Moneda cotización</label>
    <nameField>
        <displayFormat>M-{00000000}</displayFormat>
        <label>Nombre de Moneda cotización</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Moneda cotizaciones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/MonedaCotizacionTriggerTest.cls
@isTest
private class MonedaCotizacionTriggerTest {

    static testMethod void myUnitTest() {
        // TO DO: implement unit test
        Moneda__c m = new Moneda__c(name='Pesos');
        insert m;
        
        
        Moneda_cotizacion__c mc = new Moneda_cotizacion__c (moneda__c = m.id, fecha__c = Date.newInstance(2016, 12, 9), cotizacion__c = 1);

        insert mc;
        
    }
    
}