src/objects/Orden_de_compra__c.object
<CustomObject>
    <fields>
        <fullName>Fecha__c</fullName>
        <label>Fecha</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Moneda__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Moneda</label>
        <referenceTo>Moneda__c</referenceTo>
        <relationshipLabel>Ordenes de compra</relationshipLabel>
        <relationshipName>Ordenes_de_compra</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Obra__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Obra</label>
        <referenceTo>Obra__c</referenceTo>
        <relationshipLabel>Ordenes de compra</relationshipLabel>
        <relationshipName>Ordenes_de_compra</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Presupuesto__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Presupuesto</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Proveedor__c</field>
                <operation>equals</operation>
                <valueField>Presupuesto_base__c.Proveedor__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Presupuesto_base__c</referenceTo>
        <relationshipLabel>Ordenes de compra</relationshipLabel>
        <relationshipName>Ordenes_de_compra</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Proveedor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Proveedor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Proveedor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Ordenes de compra</relationshipLabel>
        <relationshipName>Ordenes_de_compra</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Responsable_carga__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Responsable carga</label>
        <referenceTo>Responsable__c</referenceTo>
        <relationshipLabel>Ordenes de compra</relationshipLabel>
        <relationshipName>Ordenes_de_compra</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sociedad__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Sociedad</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Sociedad desarrolladora</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Ordenes de compra (Sociedad)</relationshipLabel>
        <relationshipName>Ordenes_de_compra1</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Orden de compra</label>
    <nameField>
        <label>Nombre de Orden de compra</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ordenes de compra</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Orden_de_compra_entrega__c.object
<CustomObject>
    <fields>
        <fullName>Cantidad__c</fullName>
        <label>Cantidad</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Concepto__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Concepto</label>
        <referenceTo>Concepto__c</referenceTo>
        <relationshipName>Orden_de_compra_entregas</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Detalle__c</fullName>
        <label>Detalle</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Fecha_estimada_ejecucion__c</fullName>
        <label>Fecha estimada ejecucion</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Orden_de_compra__c</fullName>
        <label>Orden de compra</label>
        <referenceTo>Orden_de_compra__c</referenceTo>
        <relationshipName>Orden_de_compra_entregas</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Rubro__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Rubro</label>
        <referenceTo>Rubro__c</referenceTo>
        <relationshipName>Orden_de_compra_entregas</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tasa_impuestos__c</fullName>
        <label>Tasa impuestos</label>
        <precision>3</precision>
        <scale>1</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Valor_unitario__c</fullName>
        <label>Valor unitario</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Orden de compra detalle</label>
    <nameField>
        <displayFormat>OCE-{00000000}</displayFormat>
        <label>Nombre de Orde de compra entregas</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orden de compra detalles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Presupuesto_base__c.object
<CustomObject>
    <fields>
        <fullName>Fecha__c</fullName>
        <label>Fecha</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Moneda__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Moneda</label>
        <referenceTo>Moneda__c</referenceTo>
        <relationshipLabel>Presupuestos base</relationshipLabel>
        <relationshipName>Presupuestos_base</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Obra__c</fullName>
        <label>Obra</label>
        <referenceTo>Obra__c</referenceTo>
        <relationshipLabel>Presupuestos base</relationshipLabel>
        <relationshipName>Presupuestos_base</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Proveedor__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Proveedor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Proveedor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Presupuestos base</relationshipLabel>
        <relationshipName>Presupuestos_base</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Responsable_carga__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Responsable carga</label>
        <referenceTo>Responsable__c</referenceTo>
        <relationshipLabel>Presupuestos base</relationshipLabel>
        <relationshipName>Presupuestos_base</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sociedad__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sociedad</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Sociedad desarrolladora</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Presupuestos base (Sociedad)</relationshipLabel>
        <relationshipName>Presupuestos_base1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Presupuesto base</label>
    <nameField>
        <label>Nombre de Presupuesto base</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Presupuestos base</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Presupuesto_detalle__c.object
<CustomObject>
    <fields>
        <fullName>Cantidad__c</fullName>
        <label>Cantidad</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Concepto__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Concepto</label>
        <referenceTo>Concepto__c</referenceTo>
        <relationshipLabel>Presupuestos detalle</relationshipLabel>
        <relationshipName>Presupuestos_detalle</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Descripcion__c</fullName>
        <label>Descripcion</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Fecha_estimada_ejecucion__c</fullName>
        <label>Fecha estimada ejecucion</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Presupuesto_base__c</fullName>
        <label>Presupuesto base</label>
        <referenceTo>Presupuesto_base__c</referenceTo>
        <relationshipLabel>Presupuestos detalle</relationshipLabel>
        <relationshipName>Presupuestos_detalle</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Rubro__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Rubro</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Rubro__c.Concepto__c</field>
                <operation>equals</operation>
                <valueField>$Source.Concepto__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Rubro__c</referenceTo>
        <relationshipLabel>Presupuestos detalle</relationshipLabel>
        <relationshipName>Presupuestos_detalle</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tasa_impuestos__c</fullName>
        <label>Tasa impuestos</label>
        <precision>4</precision>
        <scale>1</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Valor_unitario__c</fullName>
        <label>Valor unitario</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Presupuesto detalle</label>
    <nameField>
        <displayFormat>PD-{00000000}</displayFormat>
        <label>Nombre de Presupuesto detalle</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Presupuestos detalle</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Rubro__c.object
<CustomObject>
    <fields>
        <fullName>Concepto__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Concepto</label>
        <referenceTo>Concepto__c</referenceTo>
        <relationshipLabel>Rubros</relationshipLabel>
        <relationshipName>Rubros</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Rubro</label>
    <nameField>
        <label>Nombre de Rubro</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rubros</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CrearOrdenDeCompra.cls
public with sharing class CrearOrdenDeCompra {
    private Presupuesto_base__c p;   

    public CrearOrdenDeCompra(ApexPages.StandardSetController controller)
    {
    }

    public CrearOrdenDeCompra(ApexPages.StandardController controller)
    {
    }

    public PageReference doSomething()    
    {
    
        ///lightning/r/Presupuesto_base__c/a0AQ000000FESPOMA5/view
        //PageReference pr = new PageReference('/lightning/r/Orden_de_compra__c/a0M1U000001fyOiUAI/view');


        this.p = [SELECT Id, Name, Obra__c, moneda__c, proveedor__c, responsable_carga__c, sociedad__c    FROM Presupuesto_base__c WHERE id =: ApexPages.CurrentPage().getparameters().get('id')  LIMIT 1];

        Orden_de_compra__c oc = new Orden_de_compra__c(name=p.name, presupuesto__c = p.id, obra__c = p.obra__c, proveedor__c = p.proveedor__c, moneda__c = p.moneda__c, responsable_carga__c = p.responsable_carga__c, sociedad__c = p.sociedad__c, fecha__c = date.today());
        insert oc;
        
        List<Presupuesto_detalle__c> results = Database.query(
            'SELECT Id, Name, concepto__c, rubro__c, descripcion__c,fecha_estimada_ejecucion__c, tasa_impuestos__c, cantidad__c, valor_unitario__c, unidad_de_medida__c ' +
            'FROM Presupuesto_detalle__c ' +
            'WHERE Presupuesto_base__c = \''+p.id + '\'' +
            'LIMIT 100'
        );
        for (Presupuesto_detalle__c pd : results) {
            Orden_de_compra_entrega__c ocd = new Orden_de_compra_entrega__c(orden_de_compra__c = oc.id, detalle__c = pd.descripcion__c, fecha_entrega_prevista__c = pd.fecha_estimada_ejecucion__c, fecha_estimada_ejecucion__c = pd.fecha_estimada_ejecucion__c,  concepto__c = pd.concepto__c, rubro__c = pd.rubro__c, cantidad__c = pd.cantidad__c, valor_unitario__c = pd.valor_unitario__c, tasa_impuestos__c = pd.tasa_impuestos__c, unidad_de_medida__c = pd.unidad_de_medida__c);
            insert ocd;
        }

        
        PageReference pr = new PageReference('/lightning/r/Orden_de_compra__c/'+oc.id+'/view');
        pr.setRedirect(true);
        return pr;
    }

}